### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by moravveji** [hpcleuven/VscDocumentation#109]
Dear GJB

The link pointing to the request form for introduction credits for KU Leuven user is either broken, or is not properly set up, because it leads to a blank page: https://vlaams-supercomputing-centrum-vscdocumentation.readthedocs-hosted.com/en/latest/leuven/credits.html#id1

Br
Ehsan

**Comment by gjbex** [comment]
@moravveji Thanks for pointing it out, fixed by PR #110
