### ISSUE TITLE
add need to request memory for superdome with the -L flag

### ISSUE THREAD

**Issue by ingridbr** [hpcleuven/VscDocumentation#126]
In superdome if the user wants to use a ratio of mem/core higher than the default it is needed to specify the memory feature in the -L command.  If this is not done when the job tries to use more than the default memory it will start swapping.  In the manual of pbs in the numa section it is explicitily mention this behaviour:

http://docs.adaptivecomputing.com/torque/6-1-3/adminGuide/torque.htm#topics/NUMA/-Lresource.htm#options

So, for example to submit of a job using 7 cores and 100GB per core  the jobs should be submitted as follows:

qsub -l partition=superdome -q qsuperdome - L tasks=1:lprocs=7:place=numanode=1:memory=700gb

**Comment by gjbex** [comment]
@ingridbr Adaptive's documentation site is currently down, so I can't verify.

This remark only applies when the required memory is
lprocs * memory per proc <= required memory <= numaplaces * memory per numaplace

Correct?

**Comment by gjbex** [comment]
Addressed by PR #137
