### ISSUE TITLE
ThinKing hardware nodemap errors

### ISSUE THREAD

**Issue by MaximeVdB** [hpcleuven/VscDocumentation#155]
There are some things that look off in the thinking_centos7.png figure of the hardware on ThinKing (shown at the bottom of [this VsCdocs page](https://vlaams-supercomputing-centrum-vscdocumentation.readthedocs-hosted.com/en/latest/leuven/tier2_hardware/thinking_hardware.html#thinking7-hardware)):

- I think the legend on the right is mostly fine, except that those two Quadro K5200 nodes are not there anymore?

- The map colors don't seem to agree with the legend. According to `pbsnodes` info,
  * the r10 racks should be red
  * the r11 and r12 racks should be salmon (that intermediate color I mean)
  * the r04i00, r04i01,  r05i00 and r05i01 don't exist (anymore?)
  * the r04i02, r05i02 and r08i00 racks should be yellow (except for those debug nodes in brown)

- Probably also good to double-check the FDR/QDR infiniband network rectangle.

**Comment by gjbex** [comment]
Should be resolved by PR #157 
Thanks @MaximeVdB 
As far as I know QDR/FDR info is correct.

**Comment by MaximeVdB** [comment]
Thank you Geert Jan for the making the changes, it looks good now!
(sorry for the delay)
