### ISSUE TITLE
Add references to MFA page

### ISSUE THREAD

**Issue by stevenvdb** [hpcleuven/VscDocumentation#283]
The MFA page explains how to use NoMachine with MFA, but on the NoMachine page itself (https://docs.vscentrum.be/en/latest/access/nx_start_guide.html#nx-start-guide) there is no mention of MFA. Could you revise that page (and probably all other pages explaining how to connect to the cluster) so that there are references to the main MFA page?

**Comment by lexming** [comment]
This is fixed, the section *NoMachine NX Client Configuration* in the [NoMachine page](https://docs.vscentrum.be/en/latest/access/nx_start_guide.html#nomachine-nx-client-configuration) now has a link to the MFA documentation.
