### ISSUE TITLE
Title bar/header

### ISSUE THREAD

**Issue by gjbex** [hpcleuven/VscDocumentation#338]
The bar at the top of the page contains a number of useful (or not so much) icons:
* Does the one to Github add value?  We don't have much material there that is public/interesting
* Can we replace the Twitter icon with the X icon?
* Can we add a LinkedIn icon since that is our main social media channel?
* Can we add an icon for the VSC website?

**Comment by lexming** [comment]
* I think so, it shows that VSC does development and users already in github can potentially reach us there
* I have to find a way to grab the new icon from FontAwesome, but it's already there so it should be doable
* Absolutetly
* We would need a small square icon of the VSC that fits in the bar, do we have any?
