### ISSUE TITLE
Lirias virtual collection label

### ISSUE THREAD

**Issue by LucIJspeert** [hpcleuven/VscDocumentation#427]
In trying to add my publication to the Virtual Collection of VSC in Lirias, I found that neither "VSC", nor “High Performance Computing” are valid labels. The latter is suggested on the FAQ site. Instead, I presume the label I found, "KUL-HPC", is the correct one to use.

I would suggest to add this in the documentation page referencing Lirias, here:
https://docs.vscentrum.be/how_do_i_acknowledge_the_vsc_in_publications.html

**Comment by stevenvdb** [comment]
Thanks for letting us know, the update has been done in https://github.com/hpcleuven/VscDocumentation/pull/428.
